### ISSUE TITLE
Add "quality" and "damage" options to the selector

### ISSUE THREAD

**Issue by noone57** [A2Bcorp/RW_A2B#26]
As request by "FamousShoes" on the forum: 

6: Quality selector: send low-quality items one way, high-quality the other.
7: Damage selector: send low-HP items one way, high-HP the other.

Initially suggested as separate "Selector units", but I think it would be best to integrate this inside the primary Selector - adding two more elements would only confuse things.

**Comment by TehJoE** [comment]
Not sure how feasible it is to actually sort on quality/HP, as I haven't
seen an instance of it in the base game, and the current selector
implementation runs on the default ITab_Storage... In any case, if it is
possible, probably a precision setting not unlike some of the item
storage/routing/filtering mods in Minecraft do for their item-id/damage
value selection would be warranted.

**Comment by noone57** [comment]
Agreed, I think it is worth waiting a bit on that one to see where Tynan is taking us. I added it here so that we don't forget about it, because it would be a rather nifty feature. But there's more 'easy' things to do for now ...

**Comment by TehJoE** [comment]
Right. Tynan's been good about implementing things that make things easier
on our end - example: the first iteration of animated belts required
intercepting the request for a Graphic_Single and replacing it on the fly
with the current animation texture, but Alpha 9 added some functions
(unless I just managed to miss them) that allowed for custom Graphic
classes to be requested in the XML, so I could just write up the
AnimatedGraphic class and use it without the game complaining. So I
wouldn't be surprised if he just tweaks the ITab_Storage to allow this
sorting by default in Alpha 10 or whatever, since weapon quality is kind of
necessary to sort by even in the base game and it's a pain to do so by hand.

**Comment by noone57** [comment]
Implemented by Tynan in A10.
