### ISSUE TITLE
Change the Selector format to be symmetric

### ISSUE THREAD

**Issue by noone57** [A2Bcorp/RW_A2B#28]
As suggested by Famous Shoes on the forum: 

" Yep, the handedness of the selector is a sticky wicket. Problematic as it is and would still be if there's a mirror-image confusing users in the build menu. I like that approach of sending matches left and right (acting as a splitter when connected on both sides) and non-matched item straight ahead; seems like only one would be needed then, no? "

Design should be changed to one input channel (South Side), one "1" exit Channel (North Side) and two "2" exit channels (Left and Right Sides) to be fed in alternance, or which ever is connected.

**Comment by TehJoE** [comment]
I like this idea since the merger will cover the lost dual input anyway.
Currently "1" maps to matched input and "2" maps to unmatched, so each of
those descriptions actually suggests routing the items differently. Should
we feed matched input to the single forward output, or to the alternating
sides? Perhaps even a toggle if both modes have strong enough use cases?
It'd be great if we could implement two separate filter sets so we could
have a 1-2-3 selector, but unfortunately that seems like it'd require
rolling our own ITab_Storage to link to a separate filter set....

**Comment by noone57** [comment]
Yeah, I think a 1-2-3 would require a fair bit of work. As per the 1 vs 2 exists, I think the system is rather symmetric, i.e. you can either enable a single item that will go straight, or alternatively enable all but that item,. which will then go sideways. And since now you can "un-select all" in the menu, that's really easy to organize things. 

So, I would simply add a second "2" exit, and let these go back and worth. Here's an updated graphic for it (will add it to the art folder later).

![selector](https://cloud.githubusercontent.com/assets/8507846/6343232/1315687a-bc39-11e4-9c8a-6c332b7f3214.png)

**Comment by TehJoE** [comment]
Cool stuff. This should be an easy one.
