### ISSUE TITLE
Underground belt system

### ISSUE THREAD

**Issue by noone57** [A2Bcorp/RW_A2B#34]
I generate possible art for the underground belt system. Names are not optimum, but here it goes. These should be useful to test the feasibility of the idea. 

Digger: should be placed on top of a "normal" belt design to give the illusion of the item disappearing underground. 

Under: Just a "floor tile" to show that there is a belt below. 

The idea would be to use a pair of "digger" exactly like the teleporter/receiver. Only because of the extra digger layout, the "jump" is not visible. Items should be stored in a list, and re-spawned after the correct time depending on the distance between the two diggers. Digger should be lined up (for now?), and every spot between them should be covered with the "Under" component. Should be a passable building, I suppose ? 

Finally, one nice feature of this system: belt lines could "cross" underground without issues. I.e. as if there was two underground layers on top of each other. In practice, it means that a single "Under" component can be crossed from either side at the same time. This should be a direct (nice) consequence of the "Digger" checking for the presence of the "Under" item, but the "Under" item not doing anything in the first place. 

Main issue: How to deal with walls ? A possible (easiest) solution is to allow them to be present between a pair of digger. I.e. between two "Diggers", you can have an "Under" item, or walls. But I think I would forbid other buildings/storage areas, etc ... because otherwise people will just build belt underground.

Ultimately, if this works well, we might want to consider removing the "teleporter/receiver" in practice, the "Underground system would allow the same thing, while possibly looking better ?  I suppose that it all depends on the "Digger", and whether the concept of "extra semi-transparent layer on top of a normal belt looks good or not.

![digger](https://cloud.githubusercontent.com/assets/8507846/6382738/4cd1dae6-bd9f-11e4-9207-5fcd914e1ca0.png)
![under](https://cloud.githubusercontent.com/assets/8507846/6382733/4b3018ce-bd9f-11e4-8e39-0f04908d1a00.png)

**Comment by TehJoE** [comment]
I believe it's possible to make floor emplacements like power conduits now,
so we can theoretically have them run under just about anything. As for
balancing that with the standard belts, perhaps an increased materials cost
and build time? And of course, more researches to unlock it. Items queued
to go through them could be lost if the unders/diggers were destroyed as
well.

One potential issue to address is how to implement deterioration -
currently there is a chance for a belt to take a small amount of damage
when an item passes over, so the "under" belts would have to be a special
case. But I'm actually reconsidering the current implementation of the
deterioration system, as it seems like it'd keep repair-designated pawns
busy all the time with small repairs.

Rendering the "digger" would actually be relatively straightforward - there
is an option for overdrawing buildings, and as I understand it, they draw
on an area larger than the actual building's location, so we could actually
make the digger 1x1 with a draw size of 2x1, so that it's built at the end
of a belt and hangs over it. Even if that's not possible, the technique
used for the ice overlay should work fine.

**Comment by noone57** [comment]
Good point about the deterioration system. I suppose it could maybe happen less often, but be stronger ... i.e. very little chance of breaking, but if it does, then it looses directly 25% of health or so. But it should be very unlikely in this case.

Also, the idea of a 2x1 image over a 1x1 item is interesting. I wonder if it would work good or not. It certainly would allow for a more convoluted design. I'll see if I get time to through something together, at least for test purposes ...

Also, I should have added it above for safekeeping, but I suspect we should be able to use the same item for both going under and above .. i.e use the same trick as the curves that can work both ways, and wait for the previous belt item to tell them what to do.

**Comment by noone57** [comment]
Underground belt system implemented using the "Undertaker" and the "Undercover".

**Comment by TehJoE** [comment]
Hey, sorry I haven't been working on this or replying at all, I've got this
game programming class that is absolutely kicking my ass with homework at
the moment so I've been busy with that literally non-stop. That should die
down soon as the semester comes to a close and I'll be able to work on it
some more, so just bear with me =)

- Joe

**Comment by noone57** [comment]
Hey, no worries !

As you'll see, I implemented the first part of the idea: 
- there is the "Undertaker" that supposedly carries items underground. In fact, they work in pairs, and just like teleporters. I.e. no item really go underground, they jump directly to the other Undertaker. But because items are hidden from view when they do this, it looks like they go below ground. 
- the "Undercover" is the same thing as a PowerCable. it is not a belt, just a tile. These must be present at all locations between two Undertaker for them to talk to each other. 

It all works fine and looks pretty good I think - especially as items are being swallowed by the undertakers. The problem right now is that the transport time is the same no matter how far apart the Undertakers are located (i.e. they behave as is next to each others).

That's because I haven't found a good way to create a list to store the items and tick them down until they "get to the other side". Definitely something I could use some help with ;-) 

Good luck with the homework !
