### ISSUE TITLE
Add queue to Undertakers

### ISSUE THREAD

**Issue by noone57** [A2Bcorp/RW_A2B#36]
Right now, the Undertaker pairs act as "teleporters", i.e. irrespective of the distance between them, the item is sent there directly (provided orientation is ok, presence of undercover between, all undercover are powered up, etc ...). 

Instead, items going under should be added to a "queue", and their exit should be delayed by the correct amount of time. Obviously, the queue should be only as long as the distance between two undertakers ...

**Comment by TehJoE** [comment]
Probably we need to catch the items in the to/from ItemContainer phase of transit... As far as the queueing of items goes, it's relatively straightforward I feel:

* Items going in are put into a List<Pair<float, Thing>>
* Every frame, we subtract off a delta-time from each float entry in the list
* Once the thing at the top of the list reaches zero, send it to the other Undertaker

Normally we'd use a queue for this, but we have to update every timer and I can't remember off hand whether the .NET Queue lets you random-access its elements. Perhaps a custom data type is appropriate here, one that syncs each timer automatically when polled. Or maybe there is an asynchronous event library contained in Rimworld/Verse/Unity/.NET, because asynchronous anything is always loads of fun. :sleepy: There are a number of different ways to handle the timing of Thing-sending, however where to actually hook that into the item transit workflow eludes me, probably because I'm a little rusty on how it all works. I did manage to stop the teleporters sending items if the receivers were clogged though so evidently it made sense to me at one point.

**Comment by noone57** [comment]
Well, I was thinking that we should catch every item on the sending side. The reason is that the sending side is checking each time a) if the receiver is there, and b), if there is an "undercover" at each location between them. 

So, whenever an item gets in, it goes in the list. The list has the size of the distance between the two ports - or the distance continuously covered by "undercovers" (the function IsConnectedUnder can be easily adapted to return that number). If one of them is destroyed, so should the top items on the list. If the list is full, the item stalls on the belt.

Whenever the top item ticks to zero, we ship it over. What that means is that if a "undercover" is destroyed, then no items pops out - we can just assume they are vaporized ... ;)

Anyway, just some thoughts ...

**Comment by ForsakenShell** [comment]
This is now handled by removing all sci-fi magic.  The undercovers and undertakers operate like any other belt component and there is a whole new multi-level system for belts.  Items now flow underground as they do above ground with the exception that the item isn't rendered for undercover components.
